CREATE TABLE IF NOT EXISTS Employee(
    EMP_ID UUID PRIMARY KEY NOT NULL,
    EMP_Name VARCHAR(100) NOT NULL,
    EMP_DateOfBirth DATE NOT NULL,
    EMP_SupervisorID UUID,
    EMP_HasCar BOOLEAN NOT NULL,
    EMP_Address VARCHAR(255) NOT NULL,
    EMP_Latitude DECIMAL(10,8) NOT NULL,
    EMP_Longitude DECIMAL(11,8) NOT NULL,
    EMP_CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMP_UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMP_SupervisorID) REFERENCES Employee(EMP_ID)
);


CREATE TABLE IF NOT EXISTS Attribute(
    ATTR_ID UUID PRIMARY KEY NOT NULL,
    ATTR_Name VARCHAR(50) NOT NULL,
    ATTR_Value VARCHAR(50) NOT NULL,
    ATTR_CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATTR_UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS EmployeeAttribute(
    EMPATTR_EMP_ID UUID NOT NULL,
    EMPATTR_ATTR_ID UUID NOT NULL,
    PRIMARY KEY(EMPATTR_EMP_ID, EMPATTR_ATTR_ID),
    FOREIGN KEY(EMPATTR_EMP_ID) REFERENCES Employee(EMP_ID),
    FOREIGN KEY(EMPATTR_ATTR_ID) REFERENCES Attribute(ATTR_ID)
);


